### ISSUE TITLE
Upgrade to Matomo 3.6

### ISSUE THREAD

**Issue by thelfensdrfer** [VisualAppeal/Matomo-PHP-API#36]
https://developer.matomo.org/changelog#piwik-300

Compatible to Matomo
* [x] 3.0
* [x] 3.1
* [x] 3.2
* [x] 3.3
* [x] 3.4
* [x] 3.5
* [x] 3.6

**Comment by thedopeyone** [comment]
Is it already compatible with piwik 3.0?

**Comment by thelfensdrfer** [comment]
There are very few changes which will affect this library, basically the ones with "http api" in the changelog. I think there are only 4 new methods which has to be implemented. Otherwise it should be compatible.

**Comment by thelfensdrfer** [comment]
@ghost Now it is.
