### ISSUE TITLE
idSite shouldn't be a mandatory construct parameter

### ISSUE THREAD

**Issue by lockland** [VisualAppeal/Matomo-PHP-API#45]
I would like to know why idSite is a construct parameter.

I'm integrating a company system with matomo and I'll have many websites to interact with and add other programatically.

I saw that this package provide an addSite method, but I cannot use it before instantiate an object, and I cannot instantiate one before have a site on matomo, so it doesnt make sense to me.

Is there any other way to add a site or create a matomo object without known the idSite?

**Comment by thelfensdrfer** [comment]
You are right. For the addSite method the siteId is superfluous. I will change it in the next release.

**Comment by lockland** [comment]
Thank you for answer fast and solve the issue faster.
